2020-06-24 15:41:41,792 ERROR: Exception on /favicon.ico [GET] [in d:\projects\learning\python-flask\venv\lib\site-packages\flask\app.py:1891
Traceback (most recent call last):
  File "d:\projects\learning\python-flask\venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\projects\learning\python-flask\venv\lib\site-packages\flask\app.py", line 1926, in dispatch_request
    self.raise_routing_exception(req)
  File "d:\projects\learning\python-flask\venv\lib\site-packages\flask\app.py", line 1908, in raise_routing_exception
    raise request.routing_exception
  File "d:\projects\learning\python-flask\venv\lib\site-packages\flask\ctx.py", line 350, in match_request
    result = self.url_adapter.match(return_rule=True)
  File "d:\projects\learning\python-flask\venv\lib\site-packages\werkzeug\routing.py", line 1945, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:\projects\learning\python-flask\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\projects\learning\python-flask\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\projects\learning\python-flask\venv\lib\site-packages\flask\app.py", line 1816, in handle_user_exception
    return self.handle_http_exception(e)
  File "d:\projects\learning\python-flask\venv\lib\site-packages\flask\app.py", line 1744, in handle_http_exception
    return handler(e)
  File "D:\projects\learning\python-flask\app\errors.py", line 6, in not_found_error
    return render_template('404.html'), 404
  File "d:\projects\learning\python-flask\venv\lib\site-packages\flask\templating.py", line 138, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "d:\projects\learning\python-flask\venv\lib\site-packages\jinja2\environment.py", line 930, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "d:\projects\learning\python-flask\venv\lib\site-packages\jinja2\environment.py", line 883, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "d:\projects\learning\python-flask\venv\lib\site-packages\jinja2\environment.py", line 857, in _load_template
    template = self.loader.load(self, name, globals)
  File "d:\projects\learning\python-flask\venv\lib\site-packages\jinja2\loaders.py", line 127, in load
    code = environment.compile(source, name, filename)
  File "d:\projects\learning\python-flask\venv\lib\site-packages\jinja2\environment.py", line 638, in compile
    self.handle_exception(source=source_hint)
  File "d:\projects\learning\python-flask\venv\lib\site-packages\jinja2\environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "d:\projects\learning\python-flask\venv\lib\site-packages\jinja2\_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "D:\projects\learning\python-flask\app\templates\404.html", line 5, in template
    <p><a href="{{ url for('index') }}">Back</a></p>
jinja2.exceptions.TemplateSyntaxError: expected token 'end of print statement', got 'for'
2020-06-24 15:42:42,055 INFO: Microblog startup [in D:\projects\learning\python-flask\app\__init__.py:47
2020-06-24 15:43:08,589 ERROR: Exception on /unfollow/artem [POST] [in d:\projects\learning\python-flask\venv\lib\site-packages\flask\app.py:1891
Traceback (most recent call last):
  File "d:\projects\learning\python-flask\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\projects\learning\python-flask\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\projects\learning\python-flask\venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "d:\projects\learning\python-flask\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "d:\projects\learning\python-flask\venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\projects\learning\python-flask\venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "d:\projects\learning\python-flask\venv\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "D:\projects\learning\python-flask\app\routes.py", line 140, in unfollow
    current_user.unfullow(user)
  File "d:\projects\learning\python-flask\venv\lib\site-packages\werkzeug\local.py", line 347, in __getattr__
    return getattr(self._get_current_object(), name)
AttributeError: 'User' object has no attribute 'unfullow'
2020-06-24 15:44:26,606 INFO: Microblog startup [in D:\projects\learning\python-flask\app\__init__.py:47
2020-06-24 16:07:52,612 INFO: Microblog startup [in D:\projects\learning\python-flask\app\__init__.py:47
2020-06-24 16:08:02,036 ERROR: Exception on / [GET] [in d:\projects\learning\python-flask\venv\lib\site-packages\flask\app.py:1891
Traceback (most recent call last):
  File "d:\projects\learning\python-flask\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\projects\learning\python-flask\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\projects\learning\python-flask\venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "d:\projects\learning\python-flask\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "d:\projects\learning\python-flask\venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\projects\learning\python-flask\venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "d:\projects\learning\python-flask\venv\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "D:\projects\learning\python-flask\app\routes.py", line 29, in index
    page = requrest.args.get('page', 1, type=int)
NameError: name 'requrest' is not defined
2020-06-24 16:08:34,451 INFO: Microblog startup [in D:\projects\learning\python-flask\app\__init__.py:47
2020-06-28 15:30:08,491 INFO: Microblog startup [in D:\projects\learning\python-flask\app\__init__.py:49
2020-06-28 15:34:22,316 INFO: Microblog startup [in D:\projects\learning\python-flask\app\__init__.py:49
2020-06-30 01:44:03,421 INFO: Microblog startup [in D:\projects\learning\python-flask\app\__init__.py:47]
